# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4240fa5c16c8f3dd0315471f0e50d4237f8b94884ffde20945bc61b545d00af0a99de9cb3ba2a88c81dce77972d32cc63c4d5021d21776e0ae435fb1eb4cdcbc

test:
  secret_key_base: 111c167ef446edc6e1a3b77058230cd16000906866948fc9c8c2b2248e21f1bfa7a66fc4e2bdd17294f6a401ab2f71e39365895981604054db8c2ca2dcea64b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
